version: '3.8'
services:
  teamproject-postgresql:
    image: postgres:14.5
    volumes:
      - ~/volumes/teamproject-1/postgresql/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
  teamproject-app:
    image: teamproject:backend
    restart: unless-stopped
    tty: true
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - teamproject-postgresql
    ports: 
      - '8000:8000'
  teamproject-frontend:
    image: teamproject:frontend
    volumes:
      - ~/volumes/teamproject-1/nginx/data:/etc/ssl
    depends_on:
      - teamproject-app
    environment:
      API_ENDPOINT: ${API_ENDPOINT}
    ports:
      - '443:443'
      - '80:80'
