version: '3.8'
services:
  teamproject-postgresql:
    image: postgres:14.5
    volumes:
      - ~/volumes/teamproject/postgresql/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: anth
      POSTGRES_PASSWORD: eevee
      POSTGRES_HOST_AUTH_METHOD: trust
  teamproject-app:
    image: teamproject_backend
    depends_on:
      - teamproject-postgresql
    ports: 
      - 8000:8000
  teamproject-frontend:
    image: teamproject_frontend
    depends_on:
      - teamproject-app
    ports:
      - 80:3000
