version: '3.8'
services:
  teamproject-postgresql:
    image: postgres:14.5
    volumes:
      - ~/volumes/teamproject/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=usersdb
      - POSTGRES_USER=anth
      - POSTGRES_PASSWORD=eevee
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 127.0.0.1:5432:5432
  teamproject-app:
    image: teamproject
    platform: 'linux/arm64/v8'
    ports: 
      - 8000:8000
