version: '3.8'
services:
  teamproject-app:
    image: teamproject
    ports: 
      - 8080:8080
  teamproject-postgresql:
    image: postgres:14.5
    volumes:
      - ~/volumes/teamproject/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=teamproject
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 127.0.0.1:5432:5432
