# Generated by Django 4.1.7 on 2023-02-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_poem_author_poem_time_created_comment_bookmark_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
