# Generated by Django 4.1.7 on 2023-03-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0009_rename_person_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='friends_list', to='poem.profile'),
        ),
    ]
