# Generated by Django 4.1.7 on 2023-03-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0011_alter_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
