# Generated by Django 4.1.7 on 2023-03-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0012_profile_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poem',
            name='matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_vote_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
