# Generated by Django 4.1.7 on 2023-04-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0016_alter_profile_profile_picture_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
