# Generated by Django 4.1.7 on 2023-04-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0017_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(default=''),
        ),
    ]
