# Generated by Django 4.1.7 on 2023-04-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0019_alter_profile_facebook_alter_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
