# Generated by Django 4.1.7 on 2023-04-15 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0020_profile_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_created',
            field=models.DateField(default=datetime.datetime(1970, 1, 1)),
        ),
    ]
