# Generated by Django 4.1.7 on 2023-04-24 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0022_theme_remove_comment_time_created_poem_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
