# Generated by Django 4.1.7 on 2023-04-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0022_theme_remove_comment_time_created_poem_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
